<?php

namespace App\Domain\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;

class CommentRequestLog extends Model
{
	use HasFactory;
	
	protected $fillable = ["total_request", "post_url", "niche_id", "user_id"];
	
	public const allowedScopes = [];
	
	public const allowedIncludes = [
		'commentLogs',
		'niche',
	];
	
	public const exactFilters = [
		"comment_log_id"
	];
	
	public const partialFilters = [
	
	];
	
	public const defaultSort = '-created_at';

  protected static function booted()
  {
    if(!is_null(Auth::user()?->id)){
      static::addGlobalScope('user', function (Builder $builder) {
        $builder->where('user_id', Auth::user()->id);
      });
    }
    parent::booted(); // TODO: Change the autogenerated stub
  }

  public function commentLogs()
	{
		return $this->hasMany(CommentLog::class);
	}
	
	public function niche()
	{
		return $this->belongsTo(Niche::class);
	}
}
