<?php

namespace App\Domain\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;

class CommentLog extends Model
{
	use HasFactory;
	
	protected $casts = [
		'debug_json' => 'json',
	];
	
	public const allowedIncludes = [
		'facebookAccount'
	];
	
	protected $fillable = [
		"facebook_account_id",
		"user_id",
		"post_url",
		"comment",
		"status",
		"debug_json",
		'comment_request_log_id',
	];
	
	public const defaultSort = '-created_at';

  public const exactFilters = ['user_id'];

  protected static function booted()
  {
    static::addGlobalScope('user', function (Builder $builder) {
      $builder->where('user_id', Auth::user()->id);
    });
    parent::booted(); // TODO: Change the autogenerated stub
  }

  public function facebookAccount()
	{
		return $this->belongsTo(FacebookAccount::class);
	}
}
